export const role_options = [
  { id: 1, value: '96', name: 'AI Researcher' },
  { id: 2, value: '100', name: 'Animator' },
  { id: 3, value: '111', name: 'Audio designer' },
  { id: 4, value: '98', name: 'Audio Engineer' },
  { id: 5, value: '94', name: 'Blockchain Developer' },
  { id: 6, value: '114', name: 'Business Analyst' },
  { id: 7, value: '117', name: 'Content Writer' },
  { id: 8, value: '127', name: 'Copywriter' },
  { id: 9, value: '122', name: 'Customer Support Specialist' },
  { id: 10, value: '95', name: 'Cybersecurity Expert' },
  { id: 11, value: '120', name: 'Data Analyst' },
  { id: 12, value: '92', name: 'Data Scientist' },
  { id: 13, value: '88', name: 'Designer' },
  { id: 14, value: '105', name: 'Editor' },
  { id: 15, value: '91', name: 'Engineer' },
  { id: 16, value: '90', name: 'Entrepreneur' },
  { id: 17, value: '124', name: 'Financial Analyst' },
  { id: 18, value: '109', name: 'Game artist' },
  { id: 19, value: '108', name: 'Game audio designer' },
  { id: 20, value: '110', name: 'Game designer' },
  { id: 21, value: '93', name: 'Game Developer' },
  { id: 22, value: '99', name: 'Graphic Designer' },
  { id: 23, value: '123', name: 'Growth Hacker' },
  { id: 24, value: '101', name: 'Illustrator' },
  { id: 25, value: '89', name: 'Marketer' },
  { id: 26, value: '126', name: 'Mobile App Developer' },
  { id: 27, value: '102', name: 'Music Producer' },
  { id: 28, value: '129', name: 'Operations Manager' },
  { id: 29, value: '106', name: 'Photographer' },
  { id: 30, value: '112', name: 'Product Designer' },
  { id: 31, value: '113', name: 'Product Manager' },
  { id: 32, value: '87', name: 'Programmer' },
  { id: 33, value: '115', name: 'Project Manager' },
  { id: 34, value: '121', name: 'Quality Assurance (QA) Tester' },
  { id: 35, value: '116', name: 'Sales Specialist' },
  { id: 36, value: '125', name: 'SEO Specialist' },
  { id: 37, value: '118', name: 'Social Media Manager' },
  { id: 38, value: '119', name: 'UI/UX Designer' },
  { id: 39, value: '128', name: 'Video Editor' },
  { id: 40, value: '107', name: 'Videographer' },
  { id: 41, value: '103', name: 'Video Producer' },
  { id: 42, value: '97', name: 'Web Developer' },
  { id: 43, value: '104', name: 'Writer' },
];

export const purpose_options = [
  { id: 1, value: '17', name: 'Freelancing together' },
  { id: 2, value: '18', name: 'Starting a business' },
  { id: 3, value: '19', name: 'Building a portfolio' },
  { id: 4, value: '20', name: 'Side project' },
  { id: 5, value: '21', name: 'Fun' },
  { id: 6, value: '22', name: 'Learning' },
  { id: 7, value: '23', name: 'Social Good' },
  { id: 8, value: '24', name: 'Escaping the 9-5' },
];
